### ISSUE TITLE
Handling multiple attached clients

### ISSUE THREAD

**Issue by VVKot** [weilbith/nvim-lsp-smag#4]
Thanks for the plugin! It works flawlessly with a single client. However, I am frequently in the position where more than one client is running, e.g. +diagnosticls, +null-ls. Is there a chance plugin can handle multiple clients correctly? I can take a stab at implementing this if you can tell me roughly what needs to be done.

**Comment by weilbith** [comment]
Hey 👋🏾 
Thanks for the nice feedback. 🙏🏾 

Hmm. That is not good. Because actually I added the handling of multiple clients. You can find it basically [here](https://github.com/weilbith/nvim-lsp-smag/blob/fa73daaaac6ca9d64de8d40a9a683229e5eb6b38/lua/lsp_smag/lsp/provider.lua#L32). So it's rather a feature but a bug that needs to be fixed.
I usually also have two servers. The "actual" one for the current language and a multi-language one for formatting and sometimes other stuff. Could you provide an exact example where this fails so I can reproduce it? That would be very helpful.
 
 Unfortunately I'm currently very busy with work and also about to travel. I need to see when I can debug it. If it is more urgent, I'm always open to review PRs and give feedback (as I can do this via phone as well).

**Comment by VVKot** [comment]
Of course when I tried it again it worked completely fine. 🤷‍♂️  Sorry for the false alarm!
