### ISSUE TITLE
Jumping on single words

### ISSUE THREAD

**Issue by jonathf** [weilbith/nvim-lsp-smag#5]
Hey, love the idea of leveraging LSP to simplify tags.

In my Python projects with ctags, my tags are single words. E.g. I have a line that says:
```
Distribution	../chaospy/distributions/baseclass/distribution.py	/^class Distribution(object):$/;"	c
```
This allows me to put the cursor on Distribution anywhere and jump with `<c-]>`.

With your plugin I don't seem to be able to do this. Instead, I need to visually select the string `chaospy.Distribution`. Then it understands the query and I can jump as normal.

Is there a way to get tag jumps to work on single words inside nvim-lsp-smag? If so, how do I enable it?

**Comment by weilbith** [comment]
Hey 👋🏾 
To be honest I'm not 100% sure if I understand you correctly. But I'm afraid that I must tell you that this does not work. As documented, this plugin doesn't actually care about your current word under your cursor, visual selection or argument of a tag command/function call. It never sees it. Instead it will query the connected language clients (and these their associated servers) for definitions/declarations/... based on the current cursor location. What the server then actually identifies as the "word"/object of interest completely belongs to the server implementation and we can't affect this. You can say that this is one of the smart features such a language server provides: detecting what is actually the object under the cursor. Completely independent of what your `iskeyword` configuration in NeoVim is. 
That said, your visual selection change nothing for the LSP part. What I suspect what is happening, is that you still have traditional tags available for the same buffer. In case the plugin was not able to find a single location for you, it will return `v:null`. In that case NeoVim will automatically fall back to use the traditional tags instead, like if you would not have set a `tagfunc` option set (as this plugin does for you). And that is actually one of the strengths this plugin that you can use both methods in parallel even for the same buffer.
So as it looks to me, in both of your cases the LSP approach does not find anything. That's why in both cases it will fall back to normal tags. In the first case it does also find nothing, as the `word` does not match any entry in your tag files. But if you make the word more specific with a visual selection it will find something.

Was that somewhat helpful? 🙈
